#!/bin/bash
set -e

DEPLOYMENTS_DIR="deployments"
BUILD_ENV="build.env"

log_error_and_exit() {
    echo "Error: $1"
    exit 1
}

# 1. Detect which folder under deployments/ has changes (git diff check)
# In a local test or simple push, we find files changed in the deployments dir
files=$(git diff --name-only HEAD^ HEAD -- "$DEPLOYMENTS_DIR" | grep -v 'template/') || true

# If no changes are found, we check the latest commit changes
if [ -z "$files" ]; then
    files=$(git diff --name-only HEAD~1 HEAD -- "$DEPLOYMENTS_DIR" | grep -v 'template/') || true
fi

# Fallback: If no git changes are detected (e.g. first run), we target the first sub-directory in deployments/
if [ -z "$files" ]; then
    # Find any directory under deployments/ that is NOT template/
    first_dir=$(find deployments -mindepth 1 -maxdepth 1 -type d | grep -v 'template' | head -n 1)
    if [ -n "$first_dir" ]; then
        files="${first_dir}/terraform.tfvars"
    else
        log_error_and_exit "No deployment found in 'deployments/'. Create one first!"
    fi
fi

# 2. Extract Deployment details
DEPLOYMENT_NAME=$(echo "$files" | cut -d '/' -f 2)
DEPLOYMENT_PATH="deployments/$DEPLOYMENT_NAME"

echo "Deployment Name: $DEPLOYMENT_NAME"
echo "Deployment Path: $DEPLOYMENT_PATH"

# Write details to build.env for subsequent jobs
echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" > "$BUILD_ENV"
echo "DEPLOYMENT_PATH=$DEPLOYMENT_PATH" >> "$BUILD_ENV"
echo "ACCOUNT_NAME=free-tier" >> "$BUILD_ENV"

export DEPLOYMENT_NAME=$DEPLOYMENT_NAME
export DEPLOYMENT_PATH=$DEPLOYMENT_PATH
export ACCOUNT_NAME="free-tier"

# Install Terragrunt dynamically on the runner container
echo "Installing Terragrunt..."
curl -sLo /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.0/terragrunt_linux_amd64
chmod +x /usr/local/bin/terragrunt

# 3. Launch Vault Agent to fetch dynamic AWS keys
echo "Launching Vault Agent..."
# We must install Vault CLI in the runner to use Vault Agent
apk add --no-cache vault --repository=https://dl-cdn.alpinelinux.org/alpine/v3.20/community/ || apk add --no-cache vault || true
vault agent -config "$CI_PROJECT_DIR/.gitlab/ci/vault-template/vault-agent.hcl"

# 4. Source AWS keys and run Terragrunt plan
echo "Sourcing temporary AWS credentials..."
if [ -f /tmp/aws-creds.env ]; then
    source /tmp/aws-creds.env
else
    log_error_and_exit "AWS credentials file /tmp/aws-creds.env was not generated by Vault Agent!"
fi

cd "$DEPLOYMENT_PATH"
terragrunt plan -input=false -out=plan.cache
